function New-Win32ToolkitUiDriverScript {
    <#
    .SYNOPSIS
        Emits the guest-side PSADT UI driver (DrivePsadtUi.ps1) into the project's Sandbox\ folder.
    .DESCRIPTION
        The driver runs IN the guest's interactive session (launched via the scheduled-task-as-user
        primitive). It launches the PSADT deploy asynchronously, then drives its dialogs with UI
        Automation: it waits for each PSADT window, screenshots it, records a state-log line, and clicks
        the intended button (Install / Defer / dismiss). It anchors on the Fluent window AutomationId
        'PSAppDeployToolkitDialog' (the dialog is rendered by PSADT.ClientServer.Client.exe, NOT the
        deploy powershell.exe, so it must NOT be matched by the deploy PID).

        The emitted script runs under Windows PowerShell 5.1 on the device, so it is written 5.1-safe
        (no ternary/??/?./&&/||, New-Object not ::new()) and saved UTF-8 WITH BOM. It is a single-quoted
        here-string: NOTHING is spliced into it. It takes only trusted literal parameters (paths, an
        action list, timeouts) and DUMPS whatever UI-Automation text it observes for the host to compare
        against the org template. Gate the result with Test-Win32ToolkitPS51Syntax before copy-in.
    .PARAMETER ProjectPath
        The PSADT project folder. The driver is written to <ProjectPath>\Sandbox\DrivePsadtUi.ps1.
    .OUTPUTS
        [string] the path to the written driver.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$ProjectPath
    )

    $sandboxDir = Join-Path $ProjectPath 'Sandbox'
    if (-not (Test-Path $sandboxDir)) { New-Item -ItemType Directory -Path $sandboxDir -Force | Out-Null }
    $driverPath = Join-Path $sandboxDir 'DrivePsadtUi.ps1'

    # Single-quoted here-string: literal, no interpolation, no injection surface. 5.1-safe throughout.
    $driver = @'
<#
    DrivePsadtUi.ps1 (generated by win32-toolkit) — GUEST-SIDE, Windows PowerShell 5.1.
    Runs in the interactive user session. Launches the PSADT deploy async, then drives its dialogs with
    UI Automation, screenshotting each and logging structured state for the host to validate.
#>
param(
    [ValidateSet('Install', 'Uninstall')] [string]$DeploymentType = 'Install',
    [string[]]$Actions = @('Install'),                 # intended clicks per Welcome dialog: Install | Defer
    [string]$DeployRoot = 'C:\PSADT',
    [string]$ShotDir = 'C:\PSADT\Sandbox\Shots',
    [string]$StateLog = 'C:\PSADT\Sandbox\Logs\uidriver-state.log',
    [int]$PerDialogTimeoutSec = 180,
    [int]$OverallTimeoutSec = 900
)

$ErrorActionPreference = 'Stop'
foreach ($d in @($ShotDir, (Split-Path -Parent $StateLog))) {
    if ($d -and -not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes
Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName System.Windows.Forms

$AE = [System.Windows.Automation.AutomationElement]
$TS = [System.Windows.Automation.TreeScope]
$CT = [System.Windows.Automation.ControlType]
$root = $AE::RootElement

function Write-State {
    param([string]$Line)
    $stamp = (Get-Date).ToString('o')
    Add-Content -LiteralPath $StateLog -Value "$stamp $Line" -Encoding UTF8
}

function New-IdCondition {
    param([string]$Id)
    New-Object System.Windows.Automation.PropertyCondition($AE::AutomationIdProperty, $Id)
}

# Top-level (Children scope) find by AutomationId. Children, not Descendants: a cross-process Descendants
# walk of the desktop root can hang.
function Wait-AdtDialog {
    param([int]$TimeoutSec)
    $cond = New-IdCondition 'PSAppDeployToolkitDialog'
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    do {
        try { $win = $root.FindFirst($TS::Children, $cond) } catch { $win = $null }
        if ($win) { return $win }
        Start-Sleep -Milliseconds 400
    } while ((Get-Date) -lt $deadline)
    return $null
}

function Get-AdtText {
    param($Win, [string]$Id)
    try {
        $e = $Win.FindFirst($TS::Descendants, (New-IdCondition $Id))
        if ($e) { return $e.Current.Name }
    } catch { }
    return ''
}

function Test-AdtElement {
    param($Win, [string]$Id)
    try { return [bool]($Win.FindFirst($TS::Descendants, (New-IdCondition $Id))) } catch { return $false }
}

function Get-AdtButtons {
    param($Win)
    $out = @()
    try {
        $cond = New-Object System.Windows.Automation.PropertyCondition($AE::ControlTypeProperty, $CT::Button)
        foreach ($b in $Win.FindAll($TS::Descendants, $cond)) {
            $out += New-Object psobject -Property @{
                Id = $b.Current.AutomationId; Text = $b.Current.Name; Enabled = $b.Current.IsEnabled
            }
        }
    } catch { }
    return $out
}

function Get-AdtSnapshot {
    param($Win)
    $b = $Win.Current.BoundingRectangle
    New-Object psobject -Property @{
        AppTitle    = $Win.Current.Name
        Subtitle    = (Get-AdtText $Win 'SubtitleTextBlock')
        Message     = (Get-AdtText $Win 'MessageTextBlock')
        Detail      = (Get-AdtText $Win 'ProgressMessageDetailTextBlock')
        Custom      = (Get-AdtText $Win 'CustomMessageTextBlock')
        Countdown   = (Get-AdtText $Win 'CountdownValueTextBlock')
        DefersLeft  = (Get-AdtText $Win 'DeferRemainingValueTextBlock')
        Deadline    = (Get-AdtText $Win 'DeferDeadlineValueTextBlock')
        HasAppIcon  = (Test-AdtElement $Win 'AppIconImage')
        HasProgress = (Test-AdtElement $Win 'ProgressBar')
        HasAppsList = (Test-AdtElement $Win 'CloseAppsListView')
        Bounds      = $b
        Buttons     = (Get-AdtButtons $Win)
    }
}

function Invoke-AdtButton {
    param($Win, [string]$Id)
    try {
        $btn = $Win.FindFirst($TS::Descendants, (New-IdCondition $Id))
        if (-not $btn) { return $false }
        $p = $btn.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern)
        $p.Invoke()
        return $true
    } catch { return $false }
}

function Save-AdtShot {
    param($Bounds, [string]$File)
    Start-Sleep -Milliseconds 250
    $x = [int]$Bounds.X; $y = [int]$Bounds.Y; $w = [int]$Bounds.Width; $h = [int]$Bounds.Height
    if ($w -le 0 -or $h -le 0) {
        $vs = [System.Windows.Forms.SystemInformation]::VirtualScreen
        $x = $vs.X; $y = $vs.Y; $w = $vs.Width; $h = $vs.Height
    }
    try {
        $bmp = New-Object System.Drawing.Bitmap($w, $h)
        $g = [System.Drawing.Graphics]::FromImage($bmp)
        $g.CopyFromScreen($x, $y, 0, 0, (New-Object System.Drawing.Size($w, $h)))
        $bmp.Save($File, [System.Drawing.Imaging.ImageFormat]::Png)
        $g.Dispose(); $bmp.Dispose()
    } catch {
        Write-State "WARN screenshot failed: $($_.Exception.Message)"
    }
}

function Save-Subtree {
    param($Win, [string]$File)
    try {
        $lines = @()
        foreach ($e in $Win.FindAll($TS::Descendants, [System.Windows.Automation.Condition]::TrueCondition)) {
            $lines += ("{0}`t{1}`t{2}" -f $e.Current.ControlType.ProgrammaticName, $e.Current.AutomationId, $e.Current.Name)
        }
        Set-Content -LiteralPath $File -Value $lines -Encoding UTF8
    } catch { }
}

function Get-DialogState {
    param($Snap)
    $enabledLeft = $false
    foreach ($b in $Snap.Buttons) { if ($b.Id -eq 'ButtonLeft' -and $b.Enabled) { $enabledLeft = $true } }
    if ($Snap.HasProgress -and -not $enabledLeft) { return 'Progress' }
    if ($Snap.HasAppsList -or ($Snap.DefersLeft -and $Snap.DefersLeft.Trim() -ne '') -or $enabledLeft) {
        if ($DeploymentType -eq 'Uninstall') { return 'UninstallWelcome' }
        return 'Welcome'
    }
    if ($Snap.Message -and $Snap.Message.Trim() -ne '') { return 'CompletionPrompt' }
    return 'Unknown'
}

function Wait-DialogGone {
    param($Win, [int]$TimeoutSec)
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    do {
        try { $null = $Win.Current.Name } catch { return $true }   # element gone -> access throws
        Start-Sleep -Milliseconds 300
    } while ((Get-Date) -lt $deadline)
    return $false
}

Write-State "SESSION_START host=$env:COMPUTERNAME user=$env:USERNAME type=$DeploymentType"

$entry = Join-Path $DeployRoot 'Invoke-AppDeployToolkit.ps1'
if (-not (Test-Path $entry)) { Write-State "RESULT ERROR missing $entry"; exit 3 }

$deploy = Start-Process powershell.exe -PassThru -ArgumentList @(
    '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $entry,
    '-DeploymentType', $DeploymentType, '-DeployMode', 'Interactive')

$overallDeadline = (Get-Date).AddSeconds($OverallTimeoutSec)
$actionIdx = 0
$seq = 0
$seen = @{}
$result = 'TIMEOUT'

while ((Get-Date) -lt $overallDeadline) {
    $win = Wait-AdtDialog -TimeoutSec 5
    if (-not $win) {
        if ($deploy.HasExited) { $result = 'COMPLETE'; break }
        continue
    }

    $seq++
    $snap = Get-AdtSnapshot $win
    $state = Get-DialogState $snap

    if (-not $seen.ContainsKey($state)) {
        $seen[$state] = $true
        Save-Subtree $win (Join-Path $ShotDir ("subtree_{0}.txt" -f $state))
    }

    $shotName = '{0:00}_{1}_{2}.png' -f $seq, $state, (Get-Date).ToString('yyyyMMddTHHmmss')
    $shotPath = Join-Path $ShotDir $shotName
    Save-AdtShot $snap.Bounds $shotPath

    $btnDesc = ''
    foreach ($b in $snap.Buttons) {
        $en = 'disabled'; if ($b.Enabled) { $en = 'enabled' }
        $btnDesc += ('{0}={1}({2});' -f $b.Id, $b.Text, $en)
    }
    Write-State ("STATE {0} app='{1}' subtitle='{2}' msg='{3}' custom='{4}' buttons='{5}' defers='{6}' countdown='{7}' hasIcon={8} hasProgress={9} hasAppsList={10} shot='{11}'" -f `
            $state, $snap.AppTitle, $snap.Subtitle, $snap.Message, $snap.Custom, $btnDesc, $snap.DefersLeft, $snap.Countdown, `
        ([int][bool]$snap.HasAppIcon), ([int][bool]$snap.HasProgress), ([int][bool]$snap.HasAppsList), $shotName)

    if ($state -eq 'Progress') {
        # Non-interactive; PSADT closes it automatically. Do not click. The 5 s poll paces the loop.
        continue
    }
    elseif ($state -eq 'Welcome' -or $state -eq 'UninstallWelcome') {
        $action = 'Install'
        if ($actionIdx -lt $Actions.Count) { $action = $Actions[$actionIdx] }
        $actionIdx++
        $clicked = $false
        if ($action -eq 'Defer') { $clicked = Invoke-AdtButton $win 'ButtonRight' }
        else { $clicked = Invoke-AdtButton $win 'ButtonLeft' }
        Write-State ("ACTION click state={0} action={1} ok={2}" -f $state, $action, ([int][bool]$clicked))
        $null = Wait-DialogGone $win $PerDialogTimeoutSec
        if ($action -eq 'Defer') { $result = 'COMPLETE'; break }   # a Defer ends the deploy; do not chain
    }
    elseif ($state -eq 'CompletionPrompt') {
        $clicked = Invoke-AdtButton $win 'ButtonRight'
        if (-not $clicked) { $clicked = Invoke-AdtButton $win 'ButtonLeft' }
        Write-State ("ACTION dismiss state=CompletionPrompt ok={0}" -f ([int][bool]$clicked))
        $null = Wait-DialogGone $win $PerDialogTimeoutSec
    }
    else {
        # Unknown: never click Install blindly. Screenshot is already saved; try a safe dismiss.
        Write-State ("ACTION unknown-dialog logged (no blind click)")
        $clicked = Invoke-AdtButton $win 'ButtonRight'
        $null = Wait-DialogGone $win 15
    }
}

Write-State ("RESULT {0} deployExited={1}" -f $result, ([int][bool]$deploy.HasExited))
if ($result -eq 'COMPLETE') { exit 0 } else { exit 2 }
'@

    [System.IO.File]::WriteAllText($driverPath, $driver, (New-Object System.Text.UTF8Encoding($true)))
    return $driverPath
}
